# Generated by Django 4.2.7 on 2026-04-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='سنوات الخبرة'),
        ),
    ]
