# Generated by Django 4.2.7 on 2026-04-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountes', '0002_user_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience_years',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مدة الخبرة'),
        ),
    ]
