# Generated by Django 4.2.7 on 2026-04-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المطبخ'),
        ),
    ]
